// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp19eODX_ZrN5evGG7dCmnEWWRnWGT2nM',
    appId: '1:879563480078:web:d2dc84606eb476aa53f05f',
    messagingSenderId: '879563480078',
    projectId: 'nexara-f6829',
    authDomain: 'nexara-f6829.firebaseapp.com',
    storageBucket: 'nexara-f6829.appspot.com',
    measurementId: 'G-YV9ME3105J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0_6SpjCgfzt4xVBctDWp8RAk9LqDZkk4',
    appId: '1:879563480078:android:4ff138a84dd6b9c353f05f',
    messagingSenderId: '879563480078',
    projectId: 'nexara-f6829',
    storageBucket: 'nexara-f6829.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfYzy94WKOXRfrZb05cOoQLHfrsE0IJ10',
    appId: '1:879563480078:ios:e239ac937cccc2d653f05f',
    messagingSenderId: '879563480078',
    projectId: 'nexara-f6829',
    storageBucket: 'nexara-f6829.appspot.com',
    iosBundleId: 'com.example.nexara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfYzy94WKOXRfrZb05cOoQLHfrsE0IJ10',
    appId: '1:879563480078:ios:e239ac937cccc2d653f05f',
    messagingSenderId: '879563480078',
    projectId: 'nexara-f6829',
    storageBucket: 'nexara-f6829.appspot.com',
    iosBundleId: 'com.example.nexara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp19eODX_ZrN5evGG7dCmnEWWRnWGT2nM',
    appId: '1:879563480078:web:496ef0a07d20db4653f05f',
    messagingSenderId: '879563480078',
    projectId: 'nexara-f6829',
    authDomain: 'nexara-f6829.firebaseapp.com',
    storageBucket: 'nexara-f6829.appspot.com',
    measurementId: 'G-JCL47N9G49',
  );
}
